package com.bioid.keycloak.client.metrics;

import io.micrometer.core.instrument.Counter;
import io.micrometer.core.instrument.Gauge;
import io.micrometer.core.instrument.MeterRegistry;
import io.micrometer.core.instrument.Timer;
import java.util.concurrent.atomic.AtomicLong;

/**
 * Comprehensive metrics collection for administrative operations.
 * Provides MicroProfile Metrics integration for monitoring administrative functions,
 * liveness detection performance, and system health indicators.
 */
public class AdminMetrics {
    private final MeterRegistry registry;

    // Administrative operation counters
    private final Counter enrollmentLinkGenerations;
    private final Counter enrollmentLinkGenerationFailures;
    private final Counter userEnrollmentDeletions;
    private final Counter userEnrollmentDeletionFailures;
    private final Counter dashboardDataRequests;
    private final Counter complianceReportGenerations;

    // Template management counters
    private final Counter templateStatusQueries;
    private final Counter templateStatusBatchQueries;
    private final Counter templateUpgrades;
    private final Counter templateUpgradeFailures;
    private final Counter templateHealthAnalyses;
    private final Counter templateCleanupOperations;

    // Liveness detection counters
    private final Counter livenessDetectionAttempts;
    private final Counter livenessDetectionSuccesses;
    private final Counter livenessDetectionFailures;
    private final Counter livenessConfigurationUpdates;
    private final Counter livenessTestOperations;

    // Bulk operation counters
    private final Counter bulkEnrollmentLinkGenerations;
    private final Counter bulkTemplateDeletions;
    private final Counter bulkTemplateUpgrades;
    private final Counter bulkOperationCancellations;
    private final Counter bulkOperationTimeouts;

    // Administrative timers
    private final Timer enrollmentLinkGenerationTimer;
    private final Timer userEnrollmentDeletionTimer;
    private final Timer dashboardDataTimer;
    private final Timer templateStatusTimer;
    private final Timer templateUpgradeTimer;
    private final Timer livenessDetectionTimer;
    private final Timer bulkOperationTimer;
    private final Timer complianceReportTimer;

    // Liveness detection mode counters
    private final Counter passiveLivenessAttempts;
    private final Counter activeLivenessAttempts;
    private final Counter challengeResponseAttempts;
    private final Counter passiveLivenessSuccesses;
    private final Counter activeLivenessSuccesses;
    private final Counter challengeResponseSuccesses;

    // System health gauges
    private final AtomicLong activeAdminSessions = new AtomicLong(0);
    private final AtomicLong activeBulkOperations = new AtomicLong(0);
    private final AtomicLong totalEnrolledUsers = new AtomicLong(0);
    private final AtomicLong templatesNeedingUpgrade = new AtomicLong(0);
    private final AtomicLong averageLivenessScore = new AtomicLong(0);

    /**
     * Creates a new AdminMetrics instance with comprehensive monitoring capabilities.
     *
     * @param registry the meter registry to use for metrics collection
     */
    public AdminMetrics(MeterRegistry registry) {
        this.registry = registry;

        // Initialize administrative operation counters
        this.enrollmentLinkGenerations = Counter.builder("bioid.admin.enrollment.link.generations")
            .description("Number of enrollment links generated by administrators")
            .register(registry);

        this.enrollmentLinkGenerationFailures = Counter.builder("bioid.admin.enrollment.link.generation.failures")
            .description("Number of failed enrollment link generations")
            .register(registry);

        this.userEnrollmentDeletions = Counter.builder("bioid.admin.enrollment.deletions")
            .description("Number of user enrollments deleted by administrators")
            .register(registry);

        this.userEnrollmentDeletionFailures = Counter.builder("bioid.admin.enrollment.deletion.failures")
            .description("Number of failed user enrollment deletions")
            .register(registry);

        this.dashboardDataRequests = Counter.builder("bioid.admin.dashboard.requests")
            .description("Number of admin dashboard data requests")
            .register(registry);

        this.complianceReportGenerations = Counter.builder("bioid.admin.compliance.report.generations")
            .description("Number of compliance reports generated")
            .register(registry);

        // Initialize template management counters
        this.templateStatusQueries = Counter.builder("bioid.admin.template.status.queries")
            .description("Number of template status queries")
            .register(registry);

        this.templateStatusBatchQueries = Counter.builder("bioid.admin.template.status.batch.queries")
            .description("Number of batch template status queries")
            .register(registry);

        this.templateUpgrades = Counter.builder("bioid.admin.template.upgrades")
            .description("Number of template upgrades performed")
            .register(registry);

        this.templateUpgradeFailures = Counter.builder("bioid.admin.template.upgrade.failures")
            .description("Number of failed template upgrades")
            .register(registry);

        this.templateHealthAnalyses = Counter.builder("bioid.admin.template.health.analyses")
            .description("Number of template health analyses performed")
            .register(registry);

        this.templateCleanupOperations = Counter.builder("bioid.admin.template.cleanup.operations")
            .description("Number of template cleanup operations performed")
            .register(registry);

        // Initialize liveness detection counters
        this.livenessDetectionAttempts = Counter.builder("bioid.admin.liveness.detection.attempts")
            .description("Number of liveness detection attempts")
            .register(registry);

        this.livenessDetectionSuccesses = Counter.builder("bioid.admin.liveness.detection.successes")
            .description("Number of successful liveness detections")
            .register(registry);

        this.livenessDetectionFailures = Counter.builder("bioid.admin.liveness.detection.failures")
            .description("Number of failed liveness detections")
            .register(registry);

        this.livenessConfigurationUpdates = Counter.builder("bioid.admin.liveness.configuration.updates")
            .description("Number of liveness configuration updates")
            .register(registry);

        this.livenessTestOperations = Counter.builder("bioid.admin.liveness.test.operations")
            .description("Number of liveness detection test operations")
            .register(registry);

        // Initialize liveness detection mode counters
        this.passiveLivenessAttempts = Counter.builder("bioid.admin.liveness.passive.attempts")
            .description("Number of passive liveness detection attempts")
            .register(registry);

        this.activeLivenessAttempts = Counter.builder("bioid.admin.liveness.active.attempts")
            .description("Number of active liveness detection attempts")
            .register(registry);

        this.challengeResponseAttempts = Counter.builder("bioid.admin.liveness.challenge.attempts")
            .description("Number of challenge-response liveness detection attempts")
            .register(registry);

        this.passiveLivenessSuccesses = Counter.builder("bioid.admin.liveness.passive.successes")
            .description("Number of successful passive liveness detections")
            .register(registry);

        this.activeLivenessSuccesses = Counter.builder("bioid.admin.liveness.active.successes")
            .description("Number of successful active liveness detections")
            .register(registry);

        this.challengeResponseSuccesses = Counter.builder("bioid.admin.liveness.challenge.successes")
            .description("Number of successful challenge-response liveness detections")
            .register(registry);

        // Initialize bulk operation counters
        this.bulkEnrollmentLinkGenerations = Counter.builder("bioid.admin.bulk.enrollment.link.generations")
            .description("Number of bulk enrollment link generations")
            .register(registry);

        this.bulkTemplateDeletions = Counter.builder("bioid.admin.bulk.template.deletions")
            .description("Number of bulk template deletions")
            .register(registry);

        this.bulkTemplateUpgrades = Counter.builder("bioid.admin.bulk.template.upgrades")
            .description("Number of bulk template upgrades")
            .register(registry);

        this.bulkOperationCancellations = Counter.builder("bioid.admin.bulk.operation.cancellations")
            .description("Number of bulk operation cancellations")
            .register(registry);

        this.bulkOperationTimeouts = Counter.builder("bioid.admin.bulk.operation.timeouts")
            .description("Number of bulk operation timeouts")
            .register(registry);

        // Initialize timers
        this.enrollmentLinkGenerationTimer = Timer.builder("bioid.admin.enrollment.link.generation.duration")
            .description("Time taken to generate enrollment links")
            .register(registry);

        this.userEnrollmentDeletionTimer = Timer.builder("bioid.admin.enrollment.deletion.duration")
            .description("Time taken to delete user enrollments")
            .register(registry);

        this.dashboardDataTimer = Timer.builder("bioid.admin.dashboard.duration")
            .description("Time taken to collect dashboard data")
            .register(registry);

        this.templateStatusTimer = Timer.builder("bioid.admin.template.status.duration")
            .description("Time taken for template status operations")
            .register(registry);

        this.templateUpgradeTimer = Timer.builder("bioid.admin.template.upgrade.duration")
            .description("Time taken for template upgrade operations")
            .register(registry);

        this.livenessDetectionTimer = Timer.builder("bioid.admin.liveness.detection.duration")
            .description("Time taken for liveness detection operations")
            .register(registry);

        this.bulkOperationTimer = Timer.builder("bioid.admin.bulk.operation.duration")
            .description("Time taken for bulk operations")
            .register(registry);

        this.complianceReportTimer = Timer.builder("bioid.admin.compliance.report.duration")
            .description("Time taken to generate compliance reports")
            .register(registry);

        // Initialize gauges
        Gauge.builder("bioid.admin.sessions.active", activeAdminSessions, AtomicLong::get)
            .description("Number of active administrative sessions")
            .register(registry);

        Gauge.builder("bioid.admin.bulk.operations.active", activeBulkOperations, AtomicLong::get)
            .description("Number of active bulk operations")
            .register(registry);

        Gauge.builder("bioid.admin.users.enrolled.total", totalEnrolledUsers, AtomicLong::get)
            .description("Total number of enrolled users")
            .register(registry);

        Gauge.builder("bioid.admin.templates.upgrade.needed", templatesNeedingUpgrade, AtomicLong::get)
            .description("Number of templates needing upgrade")
            .register(registry);

        Gauge.builder("bioid.admin.liveness.score.average", averageLivenessScore, AtomicLong::get)
            .description("Average liveness detection score (scaled by 1000)")
            .register(registry);
    }

    // Administrative operation metrics
    public void incrementEnrollmentLinkGenerations() {
        enrollmentLinkGenerations.increment();
    }

    public void incrementEnrollmentLinkGenerationFailures() {
        enrollmentLinkGenerationFailures.increment();
    }

    public void incrementUserEnrollmentDeletions() {
        userEnrollmentDeletions.increment();
    }

    public void incrementUserEnrollmentDeletionFailures() {
        userEnrollmentDeletionFailures.increment();
    }

    public void incrementDashboardDataRequests() {
        dashboardDataRequests.increment();
    }

    public void incrementComplianceReportGenerations() {
        complianceReportGenerations.increment();
    }

    // Template management metrics
    public void incrementTemplateStatusQueries() {
        templateStatusQueries.increment();
    }

    public void incrementTemplateStatusBatchQueries() {
        templateStatusBatchQueries.increment();
    }

    public void incrementTemplateUpgrades() {
        templateUpgrades.increment();
    }

    public void incrementTemplateUpgradeFailures() {
        templateUpgradeFailures.increment();
    }

    public void incrementTemplateHealthAnalyses() {
        templateHealthAnalyses.increment();
    }

    public void incrementTemplateCleanupOperations() {
        templateCleanupOperations.increment();
    }

    // Liveness detection metrics
    public void incrementLivenessDetectionAttempts() {
        livenessDetectionAttempts.increment();
    }

    public void incrementLivenessDetectionSuccesses() {
        livenessDetectionSuccesses.increment();
    }

    public void incrementLivenessDetectionFailures() {
        livenessDetectionFailures.increment();
    }

    public void incrementLivenessConfigurationUpdates() {
        livenessConfigurationUpdates.increment();
    }

    public void incrementLivenessTestOperations() {
        livenessTestOperations.increment();
    }

    // Liveness detection mode-specific metrics
    public void incrementPassiveLivenessAttempts() {
        passiveLivenessAttempts.increment();
    }

    public void incrementActiveLivenessAttempts() {
        activeLivenessAttempts.increment();
    }

    public void incrementChallengeResponseAttempts() {
        challengeResponseAttempts.increment();
    }

    public void incrementPassiveLivenessSuccesses() {
        passiveLivenessSuccesses.increment();
    }

    public void incrementActiveLivenessSuccesses() {
        activeLivenessSuccesses.increment();
    }

    public void incrementChallengeResponseSuccesses() {
        challengeResponseSuccesses.increment();
    }

    // Bulk operation metrics
    public void incrementBulkEnrollmentLinkGenerations() {
        bulkEnrollmentLinkGenerations.increment();
    }

    public void incrementBulkTemplateDeletions() {
        bulkTemplateDeletions.increment();
    }

    public void incrementBulkTemplateUpgrades() {
        bulkTemplateUpgrades.increment();
    }

    public void incrementBulkOperationCancellations() {
        bulkOperationCancellations.increment();
    }

    public void incrementBulkOperationTimeouts() {
        bulkOperationTimeouts.increment();
    }

    // Timer operations
    public Timer.Sample startEnrollmentLinkGenerationTimer() {
        return Timer.start(registry);
    }

    public void stopEnrollmentLinkGenerationTimer(Timer.Sample sample) {
        sample.stop(enrollmentLinkGenerationTimer);
    }

    public Timer.Sample startUserEnrollmentDeletionTimer() {
        return Timer.start(registry);
    }

    public void stopUserEnrollmentDeletionTimer(Timer.Sample sample) {
        sample.stop(userEnrollmentDeletionTimer);
    }

    public Timer.Sample startDashboardDataTimer() {
        return Timer.start(registry);
    }

    public void stopDashboardDataTimer(Timer.Sample sample) {
        sample.stop(dashboardDataTimer);
    }

    public Timer.Sample startTemplateStatusTimer() {
        return Timer.start(registry);
    }

    public void stopTemplateStatusTimer(Timer.Sample sample) {
        sample.stop(templateStatusTimer);
    }

    public Timer.Sample startTemplateUpgradeTimer() {
        return Timer.start(registry);
    }

    public void stopTemplateUpgradeTimer(Timer.Sample sample) {
        sample.stop(templateUpgradeTimer);
    }

    public Timer.Sample startLivenessDetectionTimer() {
        return Timer.start(registry);
    }

    public void stopLivenessDetectionTimer(Timer.Sample sample) {
        sample.stop(livenessDetectionTimer);
    }

    public Timer.Sample startBulkOperationTimer() {
        return Timer.start(registry);
    }

    public void stopBulkOperationTimer(Timer.Sample sample) {
        sample.stop(bulkOperationTimer);
    }

    public Timer.Sample startComplianceReportTimer() {
        return Timer.start(registry);
    }

    public void stopComplianceReportTimer(Timer.Sample sample) {
        sample.stop(complianceReportTimer);
    }

    // Gauge updates
    public void setActiveAdminSessions(long count) {
        activeAdminSessions.set(count);
    }

    public void incrementActiveAdminSessions() {
        activeAdminSessions.incrementAndGet();
    }

    public void decrementActiveAdminSessions() {
        activeAdminSessions.decrementAndGet();
    }

    public void setActiveBulkOperations(long count) {
        activeBulkOperations.set(count);
    }

    public void incrementActiveBulkOperations() {
        activeBulkOperations.incrementAndGet();
    }

    public void decrementActiveBulkOperations() {
        activeBulkOperations.decrementAndGet();
    }

    public void setTotalEnrolledUsers(long count) {
        totalEnrolledUsers.set(count);
    }

    public void setTemplatesNeedingUpgrade(long count) {
        templatesNeedingUpgrade.set(count);
    }

    public void setAverageLivenessScore(double score) {
        // Scale by 1000 to preserve precision in gauge
        averageLivenessScore.set((long) (score * 1000));
    }

    /**
     * Records liveness detection metrics based on mode and result.
     *
     * @param mode the liveness detection mode used
     * @param success whether the detection was successful
     * @param score the liveness score (0.0 to 1.0)
     */
    public void recordLivenessDetection(String mode, boolean success, double score) {
        incrementLivenessDetectionAttempts();
        
        switch (mode.toUpperCase()) {
            case "PASSIVE":
                incrementPassiveLivenessAttempts();
                if (success) {
                    incrementPassiveLivenessSuccesses();
                }
                break;
            case "ACTIVE":
                incrementActiveLivenessAttempts();
                if (success) {
                    incrementActiveLivenessSuccesses();
                }
                break;
            case "CHALLENGE_RESPONSE":
                incrementChallengeResponseAttempts();
                if (success) {
                    incrementChallengeResponseSuccesses();
                }
                break;
        }

        if (success) {
            incrementLivenessDetectionSuccesses();
        } else {
            incrementLivenessDetectionFailures();
        }
    }

    /**
     * Gets the current liveness detection success rate.
     *
     * @return success rate as a percentage (0.0 to 1.0)
     */
    public double getLivenessDetectionSuccessRate() {
        double attempts = livenessDetectionAttempts.count();
        double successes = livenessDetectionSuccesses.count();
        return attempts > 0 ? successes / attempts : 0.0;
    }

    /**
     * Gets the current template upgrade success rate.
     *
     * @return success rate as a percentage (0.0 to 1.0)
     */
    public double getTemplateUpgradeSuccessRate() {
        double attempts = templateUpgrades.count();
        double failures = templateUpgradeFailures.count();
        return attempts > 0 ? (attempts - failures) / attempts : 0.0;
    }
}