package com.bioid.keycloak.client.alerting;

/**
 * Types of alerts that can be generated by the BioID administrative system.
 * Each alert type represents a specific category of issue or event.
 */
public enum AlertType {
    // System Health Alerts
    SYSTEM_UNHEALTHY("System health check indicates unhealthy status"),
    SYSTEM_DEGRADED("System performance is degraded"),
    COMPONENT_FAILURE("Individual component has failed"),
    
    // Performance Alerts
    LOW_SUCCESS_RATE("Operation success rate is below threshold"),
    HIGH_RESPONSE_TIME("Response times are above acceptable threshold"),
    HIGH_ERROR_RATE("Error rate is above acceptable threshold"),
    
    // Operational Alerts
    BULK_OPERATION_FAILURE("Bulk operation has failed or partially failed"),
    TEMPLATE_UPGRADE_FAILURE("Template upgrade operation has failed"),
    LIVENESS_DETECTION_FAILURE("Liveness detection is experiencing high failure rates"),
    
    // Security Alerts
    UNAUTHORIZED_ACCESS_ATTEMPT("Unauthorized access attempt detected"),
    SUSPICIOUS_ACTIVITY("Suspicious administrative activity detected"),
    SECURITY_POLICY_VIOLATION("Security policy violation detected"),
    
    // Resource Alerts
    HIGH_MEMORY_USAGE("Memory usage is above threshold"),
    HIGH_CPU_USAGE("CPU usage is above threshold"),
    CONNECTION_POOL_EXHAUSTION("Connection pool is near or at capacity"),
    
    // Data Integrity Alerts
    DATA_INCONSISTENCY("Data inconsistency detected between systems"),
    TEMPLATE_CORRUPTION("Template data corruption detected"),
    AUDIT_LOG_FAILURE("Audit logging has failed"),
    
    // External Service Alerts
    BIOID_SERVICE_UNAVAILABLE("BioID service is unavailable or unresponsive"),
    BIOID_SERVICE_DEGRADED("BioID service performance is degraded"),
    NETWORK_CONNECTIVITY_ISSUE("Network connectivity issues detected"),
    
    // Monitoring Alerts
    MONITORING_FAILURE("Monitoring system has encountered an error"),
    METRICS_COLLECTION_FAILURE("Metrics collection has failed"),
    HEALTH_CHECK_FAILURE("Health check execution has failed");
    
    private final String description;
    
    AlertType(String description) {
        this.description = description;
    }
    
    public String getDescription() {
        return description;
    }
    
    /**
     * Checks if this alert type is related to system health.
     *
     * @return true if this is a health-related alert
     */
    public boolean isHealthAlert() {
        return this == SYSTEM_UNHEALTHY || this == SYSTEM_DEGRADED || this == COMPONENT_FAILURE;
    }
    
    /**
     * Checks if this alert type is related to performance.
     *
     * @return true if this is a performance-related alert
     */
    public boolean isPerformanceAlert() {
        return this == LOW_SUCCESS_RATE || this == HIGH_RESPONSE_TIME || this == HIGH_ERROR_RATE;
    }
    
    /**
     * Checks if this alert type is related to security.
     *
     * @return true if this is a security-related alert
     */
    public boolean isSecurityAlert() {
        return this == UNAUTHORIZED_ACCESS_ATTEMPT || 
               this == SUSPICIOUS_ACTIVITY || 
               this == SECURITY_POLICY_VIOLATION;
    }
    
    /**
     * Checks if this alert type is related to external services.
     *
     * @return true if this is an external service alert
     */
    public boolean isExternalServiceAlert() {
        return this == BIOID_SERVICE_UNAVAILABLE || 
               this == BIOID_SERVICE_DEGRADED || 
               this == NETWORK_CONNECTIVITY_ISSUE;
    }
}